name: ebook
version: 0.0.1
description: epub3 utilities
author: Stephen Holstein <sholstei@yahoo.com>
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  archive: ^3.3.7
  xml: ^6.3.0
  image: ^4.0.17
  path: ^1.8.3

dev_dependencies:
  test: ^1.0.0
  path: ^1.8.3

