name: ebook
version: 0.0.1
description: epub3 utilities
author: Stephen Holstein <sholstei@yahoo.com>
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:

dev_dependencies:
  test: ^1.0.0

